config/routes.rb
Rails.application.routes.draw do
  get '/assurances/immovable_all', to:'assurances#immovable_all'
  get '/assurances/car_all', to:'assurances#car_all'
  get '/assurances/agricultural_all', to:'assurances#agricultural_all'
  root 'assurances#index'
  resources :assurances
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agricultural.rb
class Agricultural < Assurance
  validates_presence_of :dry_zone
  validates_presence_of :culture_type
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assurance.rb
class Assurance < ApplicationRecord
    validates_presence_of :email
    validates_length_of :social_reason, minimum: 1, maximum: 20, allow_blank: false
    validates_length_of :siret, minimum: 14, maximum: 14, allow_blank: false
    validates_length_of :siren, minimum: 9, maximum: 9, allow_blank: false
    validates_length_of :naf_code, minimum: 5, maximum: 5, allow_blank: false
    validates_length_of :phone_number, minimum: 10, maximum: 10, allow_blank: false
    validates_numericality_of :siret, :siren, :annual_incomes, :phone_number
    scope :immovable, -> { where(type: "Immovable") }
    scope :agricultural, -> { where(type: "Agricultural") }
    scope :car, -> { where(type: "Car") }
    enum culture_type: [:wheat, :barley, :corn]
end

app/models/car.rb
class Car < Assurance
  validates_presence_of :car_model
  validates_length_of :licence_points, minimum: 0, maximum: 2, allow_blank: false
  validates_length_of :registration_number, minimum: 7, maximum: 7, allow_blank: false
  validates_numericality_of :licence_points, :registration_number
  store :serialized_options, accessors: [:test], coder: Hash
end

app/models/immovable.rb
class Immovable < Assurance
  validates_length_of :building_size, minimum: 0, maximum: 4, allow_blank: false
  validates_length_of :floor_number, minimum: 0, maximum: 2, allow_blank: false
  validates_numericality_of :building_size, :floor_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assurances_controller.rb
class AssurancesController < ApplicationController
  def create
    @assurance = Assurance.create(assurance_params)
    @assurance.save
      flash[:success] = 'Assurance created'
      if @assurance.type == "Immovable"
        redirect_to assurances_immovable_all_path
      elsif @assurance.type == "Car"
        redirect_to assurances_car_all_path
      elsif @assurance.type == "Agricultural"
        redirect_to assurances_agricultural_all_path
      end
  end

  def new
    @assurance = Assurance.new(params[:assurance])
  end

  def index
    @assurances = Assurance.all
  end

  def immovable_all
    @immovables = Assurance.immovable.all
  end

  def agricultural_all
    @agriculturals = Assurance.agricultural.all
  end

  def car_all
    @cars = Assurance.car.all
  end

  private

  def assurance_params
    params.require(:assurance).permit(:email, :social_reason, :siret, :siren, :naf_code, :phone_number, :annual_incomes, :phone_number, :type, :dry_zone, :culture_type, :car_model, :licence_points, :registration_number, :building_size, :floor_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assurance_helper.rb
module AssuranceHelper
end

app/views/assurances/agricultural_all.html.erb
<div style="padding:50px;color:#4d5061">
  <h1>Agricultural</h1>
  <div class="row margin-left width-100">
    <table>
      <caption>________________</caption>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Email</th>
        <th scope="col">social_reason</th>
        <th scope="col">siret</th>
        <th scope="col">siren</th>
        <th scope="col">naf_code</th>
        <th scope="col">annual_incomes</th>
        <th scope="col">phone_number</th>
        <th scope="col">culture_type</th>
        <th scope="col">dry_zone</th>

      </tr>
      <% @agriculturals.each do |a| %>
      <tr>
          <th scope="row"><%= a.id %></th>
          <td><%= a.type %></td>
          <td><%= a.email %></td>
          <td><%= a.social_reason %></td>
          <td><%= a.siret %></td>
          <td><%= a.siren %></td>
          <td><%= a.naf_code %></td>
          <td><%= a.annual_incomes %></td>
          <td><%= a.phone_number %></td>
          <td><%= a.culture_type %></td>
          <td><%= a.dry_zone %></td>
      </tr>
      <% end %>
    </table>

    </div>
  </div>
</div>

app/views/assurances/car_all.html.erb
<div style="padding:50px;color:#4d5061">
  <h1>Car</h1>
  <div class="row margin-left width-100">
    <table>
      <caption>________________</caption>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Email</th>
        <th scope="col">social_reason</th>
        <th scope="col">siret</th>
        <th scope="col">siren</th>
        <th scope="col">naf_code</th>
        <th scope="col">annual_incomes</th>
        <th scope="col">phone_number</th>
        <th scope="col">licence_points</th>
        <th scope="col">car_model</th>
        <th scope="col">registration_number</th>
      </tr>
      <% @cars.each do |c| %>
      <tr>
          <th scope="row"><%= c.id %></th>
          <td><%= c.type %></td>
          <td><%= c.email %></td>
          <td><%= c.social_reason %></td>
          <td><%= c.siret %></td>
          <td><%= c.siren %></td>
          <td><%= c.naf_code %></td>
          <td><%= c.annual_incomes %></td>
          <td><%= c.phone_number %></td>
          <td><%= c.licence_points %></td>
          <td><%= c.car_model %></td>
          <td><%= c.registration_number %></td>
      </tr>
      <% end %>
    </table>

    </div>
  </div>
</div>

app/views/assurances/create.html.erb
<h1>Assurance#create</h1>
<p>Find me in app/views/assurance/create.html.erb</p>

app/views/assurances/destroy.html.erb
<h1>Assurance#destroy</h1>
<p>Find me in app/views/assurance/destroy.html.erb</p>

app/views/assurances/edit.html.erb
<h1>Assurance#edit</h1>
<p>Find me in app/views/assurance/edit.html.erb</p>

app/views/assurances/immovable_all.html.erb
<div style="padding:50px;color:#4d5061">
  <h1>Immovable</h1>
  <div class="row margin-left width-100">
    <table>
      <caption>________________</caption>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Email</th>
        <th scope="col">social_reason</th>
        <th scope="col">siret</th>
        <th scope="col">siren</th>
        <th scope="col">naf_code</th>
        <th scope="col">annual_incomes</th>
        <th scope="col">phone_number</th>
        <th scope="col">building_size</th>
        <th scope="col">floor_number</th>
      </tr>
      <% @immovables.batch do |a| %>
      <tr>
          <th scope="row"><%= a.id %></th>
          <td><%= a.type %></td>
          <td><%= a.email %></td>
          <td><%= a.social_reason %></td>
          <td><%= a.siret %></td>
          <td><%= a.siren %></td>
          <td><%= a.naf_code %></td>
          <td><%= a.annual_incomes %></td>
          <td><%= a.phone_number %></td>
          <td><%= a.building_size %></td>
          <td><%= a.floor_number %></td>
      </tr>
      <% end %>
    </table>

    </div>
  </div>
</div>

app/views/assurances/index.html.erb
<div style="padding:50px;color:#4d5061">
  <h1>Assurance</h1>
  <div class="row margin-left width-100">
    <table>
      <caption></caption>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Type</th>
          <th scope="col">Email</th>
          <th scope="col">social_reason</th>
          <th scope="col">siret</th>
          <th scope="col">siren</th>
          <th scope="col">naf_code</th>
          <th scope="col">annual_incomes</th>
          <th scope="col">phone_number</th>
          <th scope="col">building_size</th>
          <th scope="col">floor_number</th>
          <th scope="col">culture_type</th>
          <th scope="col">dry_zone</th>
          <th scope="col">licence_points</th>
          <th scope="col">car_model</th>
          <th scope="col">registration_number</th>
      </tr>
      <% @assurances.each do |a| %>
      <tr>
          <th scope="row"><%= a.id %></th>
          <td><%= a.type %></td>
          <td><%= a.email %></td>
          <td><%= a.social_reason %></td>
          <td><%= a.siret %></td>
          <td><%= a.siren %></td>
          <td><%= a.naf_code %></td>
          <td><%= a.annual_incomes %></td>
          <td><%= a.phone_number %></td>
          <td><%= a.building_size %></td>
          <td><%= a.floor_number %></td>
          <td><%= a.culture_type %></td>
          <td><%= a.dry_zone %></td>
          <td><%= a.licence_points %></td>
          <td><%= a.car_model %></td>
          <td><%= a.registration_number %></td>
      </tr>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/assurances/new.html.erb
<div class="main-block">
  <div class="main-form">
  <h1>Thanks for trusting us</h1>
  </div>
  <div class="main-form2">
      <% if @assurance.invalid? %>
      <div class="alert alert-danger">
        <% @assurance.errors.full_messages.each do |messages| %>
        <p><%= messages %></p>
        <%end%>
      </div>
      <% end %>
      <%= form_for @assurance do |f| %>
      <h3 class="text-center small-margin-bottom font-weight-bold">Main informations</h3>
      <p>Email :</p>
      <p> <%= f.text_field :email, placeholder:"Email...", id:""%><br></p>
      <p>Phone :</p>
      <p> <%= f.text_field :phone_number, placeholder:"in 10 number", id:""%><br></p>
      <p>SIRET :  </p>
      <p><%= f.text_field :siret, placeholder:"in 14 number ", id:""%><br></p>
      <p>SIREN : </p>
      <p><%= f.text_field :siren, placeholder:"in 9 number ", id:""%><br></p>
      <p>NAF CODE  : </p>
      <p><%= f.text_field :naf_code, placeholder:"in 5 number", id:""%><br></p>
      <p>The social reason : </p>
      <p><%= f.text_field :social_reason, placeholder:"max 20 characters...", id:""%><br></p>
      <p>Annual incomes : </p>
      <p><%= f.text_field :annual_incomes, placeholder:"numbers only", id:""%> dollars<br></p>
      <p>Please set the type of your contract : </p>
      <p><%= f.select :type, options_for_select([["", ""], ["Car", "Car"],["Agricultural", "Agricultural"],["Immovable", "Immovable"]]) %></p>
      <h3 class="text-center small-margin-bottom font-weight-bold">For a agricultural contract please fill up those fields : </h3>
      <p>Set the cultural type : </p>
      <p><%= select_tag :culture_type, options_for_select(Assurance.culture_types), :include_blank => true %></p>
      <p>Check the box if it's a dry zone </p>
      <p><%= f.check_box :dry_zone %> <br /></p>
      <h3 class="text-center small-margin-bottom font-weight-bold">For a car contract please fill up those fields : </h3>
      <p>Car model </p>
      <p><%= f.text_field :car_model, placeholder:"Car model..." %> <br /></p>
      <p>Number of points left on the driving licence </p>
      <p><%= f.text_field :licence_points, placeholder:"max 99" %> <br /></p>
      <p>The 7 number of your registration number : </p>
      <p><%= f.text_field :registration_number, placeholder:"in 7 number" %> <br /></p>
      <h3 class="text-center small-margin-bottom font-weight-bold">For a immovable contract please fill up those fields : </h3>
      <p>Building size : </p>
      <p><%= f.text_field :building_size, placeholder:"in metre, max 9999" %> metre<br /></p>
      <p>Number of floor : </p>
      <p><%= f.text_field :floor_number, placeholder:"max 99" %> floor <br /></p>
      <p class="text-center margin-top"><%= f.submit class:"btn btn-outline-success" %></p>
      <p class="text-center font-italic">We will send you a quote with the price</p>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">HOGGO APP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "New assurance", new_assurance_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Index", assurances_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Immovable", assurances_immovable_all_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Car", assurances_car_all_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Agricultural", assurances_agricultural_all_path, class:'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoggoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>